name: simple python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wheel
    - name: Lint with flake8
      run: |
        flake8 package

    - name: Run tests
      run: |
        pytest test.py

    - name: Package the app
      run: |
        python setup.py sdist bdist_wheel
